### ISSUE TITLE
ss-qt5: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wonbin2011** [shadowsocks/shadowsocks-qt5#438]
centos7  run 'ss-qt5'

> ss-qt5: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No >such file or directory

ldd /usr/bin/ss-qt5

  

>       libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007ff6523bf000)
> 	libQt5Widgets.so.5 => not found
> 	libQt5Gui.so.5 => not found
> 	libQt5Network.so.5 => /lib64/libQt5Network.so.5 (0x00007ff652262000)
> 	libQt5DBus.so.5 => /lib64/libQt5DBus.so.5 (0x00007ff6521de000)
> 	libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007ff651d55000)
> 	libGL.so.1 => /lib64/libGL.so.1 (0x00007ff651ac5000)

**Comment by meoow** [comment]
Since your Qt5 libs are in /lib64/, I can tell your Qt5 is not from the CentOS 7 official repository, remove your version of Qt5, and install one through `yum` command.

**Comment by GP03DHulaki** [comment]
I also have the exactly **same problem** on CentOS 7 which says "No such file or directory" after install Shadowsocks-qt5 from this[ Official installation Guide](https://github.com/shadowsocks/shadowsocks-qt5/wiki).

And I solved this by run:
`sudo yum install qt5-qtbase-gui`

Then I can **SUCCESSFULLY** launch `ss-qt5`

After this run `ldd /usr/bin/ss-qt5`
>         libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007fc7d2221000)
>         libQt5Network.so.5 => /lib64/libQt5Network.so.5 (0x00007fc7d20c5000)

Still don't know the reason because my CentOS 7 is just installed and should be installed qt5 with official repository.

**Comment by librehat** [comment]
It's strange that the dependency wasn't addressed automatically. But thank you @GP03DHulaki
