### ISSUE TITLE
ubuntu 17.04.1 not  import gui-config.json

### ISSUE THREAD

**Issue by chenxuzhao** [shadowsocks/shadowsocks-qt5#483]

**Comment by librehat** [comment]
elaborate

**Comment by AurusHuang** [comment]
I have suffered a similar problem. When I click "Import from gui-config.json" (or similar text, as I'm using Chinese version), the program stuck. If I force quitting it, it will not be launched again. Adding servers manually is OK, however. 
Having this function normally is important, since there are users who need to import 10-20 servers at one time to switch to different servers when one server is down. 
Since this problem still exists as of now (17 Jul 2017), I request reopen this issue and hope someone to solve it. @librehat
