### ISSUE TITLE
this client doesn't work on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by javaeryang** [shadowsocks/shadowsocks-qt5#740]
it doesn't work on my system Ubuntu 18.04 LTS, i configed my server on this client, but however i can't access google.com or youtube.com

**Comment by fattypiggy** [comment]
really??? Is there anyone has the same issue? I have a Ubuntu18.04 desktop, but I haven't tried that.

**Comment by jssda** [comment]
me too

**Comment by gallimaufrystew** [comment]
compile it yourself

**Comment by csysl** [comment]
me too

**Comment by neoql** [comment]
me two

**Comment by wbq813** [comment]
still can not work

**Comment by gaoyanglion** [comment]
AppImage ？mine works well

**Comment by wbq813** [comment]
@gaoyanglion appimage do not have space to input obft parameter, how do you do this

**Comment by gaoyanglion** [comment]
obft ？i don't use it

**Comment by wbq813** [comment]
@gaoyanglion  兄弟可否私聊一波指导一下，我的没有obfs 配置，连不上

**Comment by archersmind** [comment]
I've compiled the ss-qt5 myself, but it still not working on my Ubuntu 18.04.

**Comment by Shengs** [comment]
same here, changed ‘bionic' to 'artful' in PPA; cant open google

**Comment by Beautykay** [comment]
I can't get shadowsocks-Qt5 for ubuntu 18.04 LTS........

**Comment by Beautykay** [comment]
@gaoyanglion 老哥怎么装的ss-qt5阿，我这18.04 按word提示装不上阿

**Comment by archersmind** [comment]
Hello Guys,
I know you must be struggling with the ss-qt5 problem on Ubuntu 18.04. Before it actual fixed or someone has a method to overcome this issue. I suggest using [chrome-app](https://github.com/shadowsocks/shadowsocks-chromeapp) + [SwitchyOmega](https://www.switchyomega.com/) to make ss working.

In SwitchyOmega just add a profile like this:
![ss](https://user-images.githubusercontent.com/1461331/42766848-0d60edf6-894e-11e8-947c-8d8051c481b8.png)

So, please stop posting meanless comments like "Me too", "Same here".

Thank you

**Comment by kellenf** [comment]
I used to work well in ubuntu18.04LTS  ,yesterday,before I start ss-qt5,I used the netease_cloud_music（网易云音乐）,and then,I use ss-qt5,it can connecte but the over the delay time,when i restart the system,it works well again,but I don't know why,who can give me some guids that how can I find the difference after I open 网易云音乐,which causes the ss-qt5 can't work?

**Comment by konnyakuxzy** [comment]
Emmmm... I've also had this problem before, perhaps just like the problems you encountered. My ubuntu18.04 also installed ss-qt5 from the apt source of 16.04, but it could not run. But my 18.04 can run the official appimage, so I guess it's the reason for the version. Finally, I cloned the source code and compiled it into a.DEB format installation package, which was successfully installed and used. I put it in my blog: [https://www.k-xzy.xyz/archives/6486](https://www.k-xzy.xyz/archives/6486) Maybe it will help you.:)

（~~我只是个高一学生所以英语特别差~~以上翻译来自百度）

emmmm...我之前也遇到了这个问题，也许和你们遇到的问题一样。我的ubuntu18.04也是从16.04的apt源中安装了ss-qt5但是却无法运行。但是我的18.04能运行官方提供的appimage，于是我猜测是版本的原因。最后我把源代码克隆了下来并且编译成了.DEB格式的安装包，并且成功安装使用。我把它放到了我的博客里：[https://www.k-xzy.xyz/archives/6486](https://www.k-xzy.xyz/archives/6486)。也许对你们有帮助。:)

**Comment by LJXLJXLJX** [comment]
@qsyttkx  It doesn't work, still can't get access to google

**Comment by LJXLJXLJX** [comment]
@konnyakuxzy 按照你的方法成功安装了ss 测试延迟也都可以 浏览器的proxy也配置了 国内的网都能访问但还是连不上google 一直提示超时

**Comment by librehat** [comment]
You need to configure the proxy settings in your browser. Please, 99.9% of the time it has nothing to do with this application

**Comment by isofun** [comment]
@LJXLJXLJX 我也是，解决了吗

**Comment by Dmupnsn** [comment]
After sever trials, finally get connected to Google now. Here are what I had done. Not sure whether all of them are necessary, but hope it can be useful to you guys:
1) Download Shadowsocks Appimage, change permission configuration be make it exectable; Input the information offered by your SS service supplier.
Just be careful here, the local port I used is 0 here. I tried with 1080 at first beginning(according to all the experiences shared online, they all used 1080), but it could not work. Finally I happened to notice that the default local port for my SS service is 0, so I changed all the local port to 0, in Appimage as well as in the configure files for shadowsocks and proxychains.
I guess for me that the most suspicious reason why it didn't work at the first beginning. You may need to pay attention to your local port, make it consistent with the service offered by your supplier? Not sure about that.
2) Also install the shadowsocks with sudo apt-get, and edit the configuration files with sudo gedit. 

3) Also install and edit the proxychains configure files (As mentioned above, use local port 0 here, instead of 1080);

4) Using Firefox, installed the Proxy SwitchyOmega Add on, and configure it as you can see when installing, or what you can find on internet. Nothing special.

5)After that, maybe you need to reboot the Firefox, or also your computer.

Then, open the Shadowsocks Appimage, connect with certain channel, ensure it shows connected, test Latency, if you want. if everything okay, you should be able to get access to Google now.

**Comment by Dmupnsn** [comment]
> After sever trials, finally get connected to Google now. Here are what I had done. Not sure whether all of them are necessary, but hope it can be useful to you guys:
> 
>     1. Download Shadowsocks Appimage, change permission configuration be make it exectable; Input the information offered by your SS service supplier.
>        Just be careful here, the local port I used is 0 here. I tried with 1080 at first beginning(according to all the experiences shared online, they all used 1080), but it could not work. Finally I happened to notice that the default local port for my SS service is 0, so I changed all the local port to 0, in Appimage as well as in the configure files for shadowsocks and proxychains.
>        I guess for me that the most suspicious reason why it didn't work at the first beginning. You may need to pay attention to your local port, make it consistent with the service offered by your supplier? Not sure about that.
> 
>     2. Also install the shadowsocks with sudo apt-get, and edit the configuration files with sudo gedit.
> 
>     3. Also install and edit the proxychains configure files (As mentioned above, use local port 0 here, instead of 1080);
> 
>     4. Using Firefox, installed the Proxy SwitchyOmega Add on, and configure it as you can see when installing, or what you can find on internet. Nothing special.
> 
> 
> 5)After that, maybe you need to reboot the Firefox, or also your computer.
> 
> Then, open the Shadowsocks Appimage, connect with certain channel, ensure it shows connected, test Latency, if you want. if everything okay, you should be able to get access to Google now.

Some update information: Just checked, even quit the AppImage, still be able to get access to the Google. Not necessary to edit the Network connection for the computer confirguration neither. So seems that the sudo install Shadowsocks/proxychains+Proxy switchyOmega for Firefox is enough, FYI. Just pay attention to the local port setting, still.

**Comment by kimroniny** [comment]
> In ubuntu 18.04 LTS, shadowsocks-qt5 doesn't change the network proxy settings. Although you opened shadowsocks-qt5 and clicked connet, you can't surf through it.
> 
> Open settings(system, not ss-qt5) -> network -> network proxy, switch to manual. and modify the socks host as 127.0.0.1, port 1080.
> 
> Then you can use it.

very good！！！
